language: python
branches:
  except:
    - gh-pages

cache:
  directories:
    - "${TRAVIS_BUILD_DIR}/.tox"

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.5
      env: TOXENV=py35
    - python: 3.4
      env: TOXENV=py34
    - python: 3.3
      env: TOXENV=py33
    - python: 2.7
      env: TOXENV=py27
    - python: pypy
      env: TOXENV=pypy
  allow_failures:
    - python: 3.6
      env: TOXENV=py36

install:
  - pip install tox

script:
  - tox

after_success:
  - pip install coveralls pylint
  - pylint steenzout.barcode
  - coveralls

deploy:
  provider: pypi
  user: steenzout
  password:
    secure: zBtdn9RR90o/aBzP2bcOjjRYiAhVD7m6aO/2o8stZ4Fc2idU2OrqmDO+mpHAvNy8uzRA95fWQlSxr1VAqugx4q70u+IDPf8a+E/nyoFOolYhkyROw3ScyrSwKtVIvYrnroIoaGblqcXkxF3JbDgyj2jy5JiIUSqzkLj4uOPAQf9K2wnxjhZoAP753VF/49RiVbalKc9UOJVt82LvNqXxM6YQOwtQehRvaOlBj17C18auTudIsZAcZ30cUPE/SA8QnvlVu19EfcP+dpwAgvdI46Ag0XO4m5ZOKnFmClZYqrfr6AVImXSmVqL9P2lVUCAS1yW7wkwk0QG1G+ZDY/fIenZMyktP9blVBwuss3XN80LdkVQTdFbOm2uQ25jb4mw6JWYLG+VB/Y0rXyKHuK/qq46XkaRIO6mcJMucBGvRKteBHdgpXFKVcgd8Io02p/gXwDCRCNlNUIHIAsvtR3RlUXpg44DK/Xj34LJIHFCJH3I2NE43F4DoLsOZ1tE8p9TotB0uRSoMAWwa2bnpkmgjpLBZ6dbWUu39h1SsYsnY8MnKOIGB9NNIoTukSbdDRQJTntmbGPzzoGZR8HrQAE64NqgSSKADAj1pui9kRI3h2rHk8KtPbOVjvob1BObEFzawz1BUkYH/B1t2DjQpfvpQeay5c6glEW9xJQxcr7MDODs=
  on:
    tags: true
